# Generated by Django 4.2.7 on 2024-11-04 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_alter_cart_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ('id',), 'verbose_name': 'Cart', 'verbose_name_plural': 'Carts'},
        ),
    ]
